# Generated by Django 3.2.13 on 2023-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=50)),
                ('nivelAgitado', models.CharField(choices=[('S', 'Sempre'), ('N', 'Nunca'), ('A', 'As vezes')], max_length=1)),
                ('expecVida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TerAnimais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('resumo', models.CharField(max_length=80)),
                ('genero', models.CharField(max_length=50)),
                ('dataLancamento', models.DateField()),
            ],
        ),
    ]
